#!/usr/bin/env python3
"""Derive the refusal-code crosswalk between this rail and the reference.

Every figure the crosswalk publishes is computed here from two inputs and no
other: this repository's own run report, and the conformance corpus as
published. Nothing is typed in by hand, so a reader who disagrees with a number
can regenerate it, and need not take it on trust.

Inputs
    reports/after-resolution/first-run.json   this rail's codes, per vector
    corpus/vectors/MANIFEST.json              the reference's codes, per vector
    corpus/vectors/reject/INDEX.md            the condition registry and its
                                              spec line anchors

The pivot is the corpus's own condition identifiers. Neither vocabulary owns
them: they are the suite's index into the specification text, carried with line
anchors into the vendored spec. Mapping both vocabularies onto that third thing
is the only way to relate them without one being renamed toward the other.

Usage: python3 tools/crosswalk-gen.py [--out DIR]
Exit 0 on success, 2 if an input is missing or an invariant fails.
"""

from __future__ import annotations

import argparse
import collections
import hashlib
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
RUN = ROOT / "reports" / "after-resolution" / "first-run.json"
MANIFEST = ROOT / "corpus" / "vectors" / "MANIFEST.json"
INDEX = ROOT / "corpus" / "vectors" / "reject" / "INDEX.md"

#: Match vocabulary borrowed from agent-evidence-vocabulary's own
#: `crosswalk_match_types`. Reused, not reinvented, so the filing speaks
#: the registry's language; the meanings are theirs, not redefined here.
EXACT = "exact"
STRUCTURAL = "structural"
PARTIAL = "partial"
NO_MAPPING = "no_mapping"


def die(message):
    sys.stderr.write("crosswalk-gen: %s\n" % message)
    raise SystemExit(2)


def sha256_file(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_conditions():
    """Registry rows: condition id -> (spec line anchors, prose)."""
    if not INDEX.exists():
        die("missing %s -- clone the corpus first" % INDEX)
    text = INDEX.read_text(encoding="utf-8")
    registry = {}
    row = re.compile(r"^\|\s*(aee-c-\d+)\s*\|\s*([^|]*?)\s*\|\s*(.*?)\s*\|\s*$", re.M)
    for match in row.finditer(text):
        cid, anchors, prose = match.groups()
        # The registry table comes first; later tables repeat the id per vector.
        # Keep the first occurrence, which is the definition.
        if cid not in registry:
            registry[cid] = (anchors.strip(), prose.strip())
    if not registry:
        die("no condition rows parsed from %s" % INDEX)
    return registry


def load_rows():
    """Reject vectors carrying both rails' codes."""
    if not RUN.exists():
        die("missing %s -- run the harness first" % RUN)
    report = json.loads(RUN.read_text(encoding="utf-8"))
    rows = [r for r in report["rows"] if r.get("expected_codes")]
    if not rows:
        die("run report carries no rows with expected_codes")
    return report, rows


def classify(mine, theirs, mine_sets, their_sets):
    """How this rail's code relates to the reference's, by refusal extension.

    The only relation observable from a run is which statements each code
    refuses. Two codes that refuse exactly the same statements are related
    exactly; one whose statements are a strict subset is a finer cut of the
    other; anything else overlaps partially. This is a statement about the
    corpus, never about the definitions, and the crosswalk says so.
    """
    a, b = mine_sets[mine], their_sets[theirs]
    if a == b:
        return EXACT
    if a < b or b < a:
        return STRUCTURAL
    if a & b:
        return PARTIAL
    return NO_MAPPING



def write_markdown(document, registry, out):
    """The same figures as the JSON, in the order a reader meets them."""
    counts = document["counts"]
    lines = []
    add = lines.append
    add("# Refusal-code crosswalk: `aee-e2` and the reference verifier")
    add("")
    add("Generated by `tools/crosswalk-gen.py` in")
    add("<https://github.com/DrVelvetFog/aee-e2>. Every figure below is derived from")
    add("the two files named under `derived_from` in the JSON beside this one, and")
    add("each carries its sha256 there. Nothing here is typed in by hand.")
    add("")
    add("## What this relates, and what it does not")
    add("")
    add("The suite's `comparisonSurface` marks `verdict` and `result` normative and")
    add("refusal `codes` measured. So neither vocabulary is proposed here as a")
    add("correction of the other, and nothing below asks either rail to rename a")
    add("code. Both are mapped onto a third thing: the suite's own condition")
    add("identifiers, which carry line anchors into the vendored specification.")
    add("")
    add("Every relation is extensional. Two codes are called `exact` when they")
    add("refuse the same statements across this corpus at this revision, which is a")
    add("fact about %d vectors and not a claim that two definitions mean the same"
        % counts["reject_vectors_compared"])
    add("thing. A pair agreeing on all of them may still part on the next one.")
    add("")
    add("| figure | value |")
    add("| --- | --- |")
    add("| reject vectors compared | %d |" % counts["reject_vectors_compared"])
    add("| codes declared, this rail | %d |" % counts["codes_this_rail"])
    add("| codes declared, reference | %d |" % counts["codes_reference"])
    add("| verbatim overlap | %d |" % counts["verbatim_overlap"])
    add("| pairs refusing the same set | %d |" % counts["exact_pairs"])
    add("| reference codes with no such pair | %d |"
        % counts["reference_codes_without_an_exact_pair"])
    add("| conditions in the suite registry | %d |" % len(registry))
    add("")
    add("## Pairs that refuse the same statements")
    add("")
    add("These %d are the crosswalk's spine. Each row is a pair whose refusal sets"
        % counts["exact_pairs"])
    add("are identical over the corpus; no code appears twice in the table, so the")
    add("correspondence is one-to-one as far as it reaches.")
    add("")
    add("| `aee-e2` | reference | vectors |")
    add("| --- | --- | --- |")
    for entry in document["codes"]:
        for partner in entry["reference_codes"]:
            if partner["match"] == "exact":
                add("| `%s` | `%s` | %d |"
                    % (entry["code"], partner["code"], partner["co_refusals"]))
    add("")
    add("## Where the two vocabularies cut differently")
    add("")
    add("The remaining codes carry no one-to-one partner. The table gives each")
    add("code's strongest overlap and the count behind it, which is the honest")
    add("shape of the disagreement: the two rails divide the same refusals into")
    add("different numbers of reasons.")
    add("")
    add("| `aee-e2` | refusals | strongest overlap (reference) | shared |")
    add("| --- | --- | --- | --- |")
    for entry in document["codes"]:
        if any(p["match"] == "exact" for p in entry["reference_codes"]):
            continue
        if entry["reference_codes"]:
            best = entry["reference_codes"][0]
            add("| `%s` | %d | `%s` | %d |"
                % (entry["code"], entry["refusals"], best["code"],
                   best["co_refusals"]))
        else:
            add("| `%s` | %d | none | 0 |" % (entry["code"], entry["refusals"]))
    add("")
    add("## Reference codes with no one-to-one partner here")
    add("")
    add("Stated so the gap is visible from both directions.")
    add("")
    for code in document["reference_codes_without_an_exact_pair"]:
        add("- `%s`" % code)
    add("")
    add("## Limits")
    add("")
    for limit in document["limits"]:
        add("- %s" % limit)
    add("")
    (out / "aee-e2-refusal-codes.md").write_text("\n".join(lines) + "\n",
                                                 encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default=str(ROOT / "crosswalk"))
    args = parser.parse_args()
    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    registry = load_conditions()
    report, rows = load_rows()
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))

    mine_sets = collections.defaultdict(set)
    their_sets = collections.defaultdict(set)
    cond_mine = collections.defaultdict(collections.Counter)
    cond_theirs = collections.defaultdict(collections.Counter)
    pair = collections.Counter()

    for index, row in enumerate(rows):
        # A statement can carry the same code twice: findings accumulate, and
        # one rule can be refused once per offending record. The crosswalk
        # counts STATEMENTS refused, so each code counts once per vector here.
        # Counting the raw list instead let a pair report more shared vectors
        # than either code had refusals, which is how this was caught.
        mine_here = sorted(set(row["codes"]))
        theirs_here = sorted(set(row["expected_codes"]))
        for code in mine_here:
            mine_sets[code].add(index)
        for code in theirs_here:
            their_sets[code].add(index)
        for code in mine_here:
            for other in theirs_here:
                pair[(code, other)] += 1
        for condition in row.get("conditions") or []:
            for code in mine_here:
                cond_mine[condition][code] += 1
            for code in theirs_here:
                cond_theirs[condition][code] += 1

    entries = []
    for mine in sorted(mine_sets):
        partners = sorted(
            (t for t in their_sets if pair[(mine, t)]),
            key=lambda t: (-pair[(mine, t)], t),
        )
        entries.append(
            {
                "code": mine,
                "refusals": len(mine_sets[mine]),
                "reference_codes": [
                    {
                        "code": t,
                        "co_refusals": pair[(mine, t)],
                        "reference_refusals": len(their_sets[t]),
                        "match": classify(mine, t, mine_sets, their_sets),
                    }
                    for t in partners
                ],
                "conditions": sorted(
                    (c for c in cond_mine if mine in cond_mine[c]),
                    key=lambda c: int(c.rsplit("-", 1)[1]),
                ),
            }
        )

    for entry in entries:
        for partner in entry["reference_codes"]:
            if partner["co_refusals"] > min(entry["refusals"],
                                            partner["reference_refusals"]):
                die("invariant failed: %s/%s shares %d of %d/%d"
                    % (entry["code"], partner["code"], partner["co_refusals"],
                       entry["refusals"], partner["reference_refusals"]))

    exact = [
        (e["code"], p["code"])
        for e in entries
        for p in e["reference_codes"]
        if p["match"] == EXACT
    ]

    unmatched_theirs = sorted(
        t for t in their_sets if not any(
            p["code"] == t and p["match"] == EXACT
            for e in entries for p in e["reference_codes"]
        )
    )

    document = {
        "source": {
            "standard": "AEE (Adversarial Execution Evidence)",
            "version": "v0.7",
            "rail": "aee-e2",
            "url": "https://github.com/DrVelvetFog/aee-e2",
            "role": "verifier",
            "note": (
                "An independent second implementation filed under ITE#63 E2. It "
                "validates statements and issues none, so every value it "
                "produces is computed from a statement another party signed."
            ),
        },
        "target": {
            "standard": "AEE reference verifier",
            "url": "https://github.com/astrogilda/agent-evidence-vectors",
            "suite_revision": manifest.get("suite"),
            "corpus_digest": manifest.get("corpusDigest"),
            "spec_digest": manifest.get("specDigest"),
            "spec_upstream_commit": manifest.get("specUpstreamCommit"),
        },
        "pivot": {
            "kind": "corpus condition identifiers",
            "source_file": "vectors/reject/INDEX.md",
            "conditions_registered": len(registry),
            "note": (
                "Both vocabularies are mapped onto the suite's own condition "
                "identifiers, which carry line anchors into the vendored spec. "
                "Neither rail owns them, so neither is renamed toward the other."
            ),
        },
        "crosswalk_kind": "vocabulary-to-vocabulary, over a shared corpus",
        "generated_by": "tools/crosswalk-gen.py",
        "derived_from": {
            "run_report": {
                "path": "reports/after-resolution/first-run.json",
                "sha256": sha256_file(RUN),
            },
            "manifest": {
                "path": "corpus/vectors/MANIFEST.json",
                "sha256": sha256_file(MANIFEST),
            },
            "index": {
                "path": "corpus/vectors/reject/INDEX.md",
                "sha256": sha256_file(INDEX),
            },
        },
        "counts": {
            "reject_vectors_compared": len(rows),
            "codes_this_rail": len(mine_sets),
            "codes_reference": len(their_sets),
            "verbatim_overlap": len(set(mine_sets) & set(their_sets)),
            "exact_pairs": len(exact),
            "reference_codes_without_an_exact_pair": len(unmatched_theirs),
        },
        "limits": [
            "Every relation here is extensional: it says which statements two "
            "codes both refuse, across one corpus at one revision. It is not a "
            "claim that the two definitions mean the same thing, and a pair "
            "that agrees on 272 vectors may still diverge on the 273rd.",
            "Codes are measured and not scored under the suite's "
            "comparisonSurface, so nothing here proposes that either rail "
            "adopt the other's spelling.",
            "This rail refuses every reject vector, so no row below rests on a "
            "disagreement about whether a statement is invalid. The crosswalk "
            "relates reasons given for refusals both rails already share.",
        ],
        "codes": entries,
        "reference_codes_without_an_exact_pair": unmatched_theirs,
    }

    (out / "aee-e2-refusal-codes.json").write_text(
        json.dumps(document, indent=2, sort_keys=False) + "\n", encoding="utf-8"
    )

    counts = document["counts"]
    print("reject vectors compared          : %d" % counts["reject_vectors_compared"])
    print("codes, this rail / reference     : %d / %d"
          % (counts["codes_this_rail"], counts["codes_reference"]))
    print("verbatim overlap                 : %d" % counts["verbatim_overlap"])
    print("exact pairs (same refusal set)   : %d" % counts["exact_pairs"])
    print("reference codes with no exact pair: %d"
          % counts["reference_codes_without_an_exact_pair"])
    print("conditions registered            : %d" % len(registry))
    write_markdown(document, registry, out)
    print("wrote %s" % (out / "aee-e2-refusal-codes.json"))
    print("wrote %s" % (out / "aee-e2-refusal-codes.md"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
